# Create a new user
mutation createUser($user: UserInput!) {
  createUser(data: $user) {
    _id
    _ts
    username
  }
}

# Retrieve paginated users. Defaults to all!
query getUsers($perPage: Int, $cursor: String) {
  allUsers(_size: $perPage, _cursor: $cursor) {
    data {
      _id
      _ts
      username
    }
    before
    after
  }
}

query User($username: String!) {
  findUserByUsername(username: $username) {
    _id
    _ts
    username
    tracks {
      data {
        _id
        _ts
        title
        file
        description
      }
    }
  }
}

mutation createTag($tag: TagInput!) {
  createTag(data: $tag) {
    _id
    _ts
    name
    color
    tracks {
      data {
        _id
        _ts
        title
      }
    }
  }
}

query findTag($name) {
  findTagByName(name: $name) {
    _id
    _ts
    name
    color
    tracks {
      data {
        _id
        _ts
        title
      }
    }
  }
}
